name: Auto Update Debezium Fork

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: 
    - "PLT-831"
  workflow_dispatch:

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main
        
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: main
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.GIT_HUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: debezium/debezium-server
        # Set test_mode true to run tests instead of the true action!!
        test_mode: true

    - name: Timestamp
      run: date